### ISSUE TITLE
Swiftmailer + resetting password fosuserbundle

### ISSUE THREAD

**Issue by houssemtayech** [symfony/swiftmailer-bundle#157]
I used swiftmailer to reset member (using FosUserBundle) password 
in parameters.yml:

```
mailer_transport: gmail
mailer_host: smtp.gmail.com
mailer_user: user@gmail.com
mailer_password: password
```
in config.yml:

```
swiftmailer:
    transport: smtp
    encryption: ssl
    auth_mode:  login
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
```
config_dev.yml:

```
swiftmailer:
    transport: gmail
    username:  '%mailer_user%'
    password:  '%mailer_password%'
```
config_test.yml:

```
swiftmailer:
    disable_delivery: true

```
when i test it in localhost all works fine, but when i upload the project to my server, all work good except the swiftmailer. 
I ask for resetting user password but i don't receive any thing
I'm using symfony 2.8
