### ISSUE TITLE
[Configuration] Using env() for encryption throws an exception

### ISSUE THREAD

**Issue by vudaltsov** [symfony/swiftmailer-bundle#170]
```yml
swiftmailer:
    transport:  '%env(MAILER_TRANSPORT)%'
    host:       '%env(MAILER_HOST)%'
    port:       '%env(MAILER_PORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    username:   '%env(MAILER_USER)%'
    password:   '%env(MAILER_PASS)%'
```

This config throws a `The "%env(MAILER_ENCRYPTION)%" encryption is not supported` exception.

This happens because of the `->ifNotInArray(array('tls', 'ssl', null))` check. `ContainerBuilder::resolveEnvPlaceholders` happens later.
