### ISSUE TITLE
Error when i use spool type file and stream_options (ssl)

### ISSUE THREAD

**Issue by thedarsideofit** [symfony/swiftmailer-bundle#172]
Hi guys I have an error when i set this config in my mailer
```
            encryption: tls
            stream_options:
                ssl:
                    verify_peer: false
                    verify_peer_name: false
                    allow_self_signed: true
            spool:
                type: file
                path: '%kernel.root_dir%/swiftmailer/spool'                
```
I think that is because SpoolTansport doesn't have a method setStreamOptions and then when Swift_Transport_EsmtpTransport is called the array value  was lost
I tried forcing the configuration in setStreamOptions in Swift_Transport_EsmtpTransport and then the command work
`php app/console swiftmailer:spool:send --message-limit=10 --env=dev`

Sorry for my english, thanks!
