### ISSUE TITLE
Abstract definition in service

### ISSUE THREAD

**Issue by ricknox** [symfony/swiftmailer-bundle#214]
### Overview card

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | unknown
| Bundle version  | 3.1.6

### Issue description

I am using a custom mailer class to add some special variables to the email. Here I also inject Twig but that is irrelevant for this issue. The class constructor:

```php
/**
 * Mailer constructor.
 *
 * @param \Swift_Mailer $swiftMailer
 * @param \Twig_Environment $twigEnvironment
 */
public function __construct(\Swift_Mailer $swiftMailer, \Twig_Environment $twigEnvironment)
{
    $this->swiftMailer = $swiftMailer;
    $this->twig = $twigEnvironment;
}
```

When registering the class as a service:

```yaml
parameters:
    app.mailer_class: App\Library\Mailer

services:
    app.mailer:
        class: '%app.mailer_class%'
        arguments:
            - '@swiftmailer.mailer.abstract'
            - '@twig'
```

I am getting the following error: `The service "app.mailer" has a dependency on a non-existent service "swiftmailer.mailer.abstract".` It seems that it should never consider abstract definitions to be auto wirable. (Note: `@mailer` cannot be found).
