### ISSUE TITLE
Allow stream_options when using url

### ISSUE THREAD

**Issue by amonares** [symfony/swiftmailer-bundle#220]
Hi I was expected to allow stream_options when using url, but not.

This dont work:
```yaml
swiftmailer:
  url: smtp://domain:465?encryption=ssl&auth_mode=login&username=the-user&password=the-pass
  spool: { type: 'memory' }
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false
```
But this configuration work flawless:
```yaml
swiftmailer:
  transport:        smtp
  username:         the-user
  password:         the-pass
  host:             domain
  port:             465
  encryption:       ssl
  auth-mode:        login
  spool: { type: 'memory' }
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false
```
Or is there a form to pass the stream_options into the URL form.

Best regards, thanks for the work
Álvaro Monares G.
