### ISSUE TITLE
Attempted to load class "Swift_Transport_Esmtp_Auth_CramMd5Authenticator" from the global namespace

### ISSUE THREAD

**Issue by qlerebours** [symfony/swiftmailer-bundle#243]
Hello ! 

i'm trying to send a mail with Symfony in a controller. Here is my code:

```
public function testSendMailAction() {
        $mailer = $this->container->get('mailer');

        $message = (new \Swift_Message('Hello Email'))
            ->setFrom('an.email@gmail.com')
            ->setTo('another.email@gmail.com')
            ->setBody('You should see me from the profiler!')
        ;

        $mailer->send($message);

        return new JsonResponse("Tried to send mail");
    }
```

The configuration:
```
    parameters:
        mailer_transport: gmail
        mailer_user: xxxxxxx@gmail.com
        mailer_password:   'mypassword'

    swiftmailer:
        transport: "%mailer_transport%"
        username:  "%mailer_user%"
        password:  "%mailer_password%"
        spool: { type: memory }
```

The error i get: 

![image](https://user-images.githubusercontent.com/17043042/39092402-40253866-460d-11e8-82d9-cf5bce0e87e2.png)

My composer.json:
```
    "symfony/symfony": "3.4.*",
    "symfony/swiftmailer-bundle": "^3.2",
```

Can anyone help me please ?
