### ISSUE TITLE
Multiple delivery addresses from .env

### ISSUE THREAD

**Issue by spasat** [symfony/swiftmailer-bundle#245]
I would like to have delivery addresses on different environments. 
ex:
.env
`DELIVERY_ADDRESSES='["email1@test.com", "email2@test.com"]'`
and in config/swiftmailer.yaml
`
swiftmailer: 
    delivery_addresses: '%env(json:DELIVERY_ADDRESSES)%'
`

Currently this fails because delivery_addresses expect an array but symfony transform %env(json:DELIVERY_ADDRESSES)% into a token that is parsed lately.

Is somehow a possibility to make this work?

**Comment by nicoschoenmaker** [comment]
We're also having problems with this.

The problem is basically that the [array_filter](https://github.com/symfony/swiftmailer-bundle/pull/171/files) introduced in #171 does not work because at that point the values are still represented as `env_somehash_MAILER_DELIVERY_ADDRESS_somehash`. Thus they are not filtered out, causing the [Swift_Plugins_RedirectingPlugin](https://github.com/swiftmailer/swiftmailer/blob/master/lib/classes/Swift/Plugins/RedirectingPlugin.php) to be activated.

Did manage to work around the issue (bit of a hack though): add this class somewhere
```php
namespace App\EventListener;

class DeliveryAddressesPlugin implements \Swift_Events_SendListener
{
    private $plugin;
    private $delivery_addresses;

    /**
     * @param \Swift_Events_SendListener $plugin
     * @param string[] $delivery_addresses
     */
    public function __construct(\Swift_Events_SendListener $plugin, array $delivery_addresses)
    {
        $this->plugin             = $plugin;
        $this->delivery_addresses = array_filter($delivery_addresses);
    }

    /**
     * {@inheritdoc}
     */
    public function beforeSendPerformed(\Swift_Events_SendEvent $evt)
    {
        if (empty($this->delivery_addresses)) {
            return;
        }
        $this->plugin->beforeSendPerformed($evt);
    }

    /**
     * {@inheritdoc}
     */
    public function sendPerformed(\Swift_Events_SendEvent $evt)
    {
        if (empty($this->delivery_addresses)) {
            return;
        }
        $this->plugin->sendPerformed($evt);
    }
}
```
And this to a services.yaml
```yaml
services:
    App\EventListener\DeliveryAddressesPlugin:
        decorates: swiftmailer.mailer.default.plugin.redirecting
        arguments:
            - '@App\EventListener\DeliveryAddressesPlugin.inner'
            - "%swiftmailer.mailer.default.delivery_addresses%"
```
