### ISSUE TITLE
Spool:send command ignores environment with spool's type 'file'

### ISSUE THREAD

**Issue by proArtex** [symfony/swiftmailer-bundle#247]
Symfony: 4.0.11
Bundle: 3.2.2

Here is my config:
```
swiftmailer:
    url: '%env(MAILER_URL)%'
    spool:
        type: 'file'
        path: '%kernel.project_dir%/var/mails'
```
and command:
```bin/console swiftmailer:spool:send --env=dev```

It sends emails generated by any environment.

**Comment by kojiDev** [comment]
`--env` argument means that Kernel will be initiated with that environment, and is common argument for console command.
It has no idea which mails you sent from where.
If you want to send mail from different environments that you have to set up different spools/spool paths per environment:

swiftmailer.yaml:
```
swiftmailer:
    spool:
        type: 'file'
        path: '%kernel.project_dir%/var/%kernel.environment%/mails'
```
