### ISSUE TITLE
Using an env var for the disable_delivery option doesn't work as expected

### ISSUE THREAD

**Issue by samfahmie** [symfony/swiftmailer-bundle#290]
When using a configuration like this:

```
swiftmailer:
    disable_delivery: "%env(TEST_MAIL_DISABLE_DELIVERY)%"
    # send all emails to a specific address
    delivery_addresses:
        - "%env(TEST_MAIL_DELIVERY_ADDRESS)%"
```

the value of TEST_MAIL_DISABLE_DELIVERY is ignored, and delivery is always disabled. Furthermore, if that env var isn't used anywhere else, the container will fail to build saying that this variable is unused.

The only solution I have right now is use php for the configuration, parse out the env value manually, and assign the value that way. But, this setting should use the env var value like any other.
