### ISSUE TITLE
Two mailers share the same auth handler

### ISSUE THREAD

**Issue by rolandow** [symfony/swiftmailer-bundle#73]
I am trying to use two different mailers from my console command. The problem is that the username / password seems to be overwritten. I checked on #symfony IRC where I was told that they apparently share the same auth handler.

I wrote a MailHandler with this service config:

``` YAML
mailhandler:
    class: %mailhandler.class%
    arguments: [@logger, @swiftmailer.mailer.local_mailer, @swiftmailer.mailer.sendgrid_mailer]
```

My swiftmailer config is as follows:

``` YAML
swiftmailer:
    default_mailer: local_mailer
    mailers:

        sendgrid_mailer:
            transport: smtp
            host: smtp.sendgrid.net
            port: 587
            encryption: ~
            username: xxx
            password: xxx
            antiflood:
                threshold: 99
                sleep: 2

        local_mailer:
            transport: smtp
            host: 127.0.0.1
            port: 587
            encryption: ~
            username: null
            password: null
            antiflood:
                threshold: 99
                sleep: 2
```

Now when I log some stuff in my MailHandler:

``` PHP
    public function __construct($logger, $measureMailer, $sendGridMailer) {
        $this->logger = $logger;

        $this->measureMailer = $measureMailer;
        $this->logger->debug("Measuremail host: ".$this->measureMailer->getTransport()->getHost()." user: ".$this->measureMailer->getTransport()->getUsername());

        $this->sendGridMailer = $sendGridMailer;
        $this->logger->debug("Sendgrid host: ".$this->sendGridMailer->getTransport()->getHost()." user: ".$this->sendGridMailer->getTransport()->getUsername());


        echo "var dump";
        var_dump($this->measureMailer->getTransport()->getUsername() === $this->sendGridMailer->getTransport()->getUsername());
    }
```

It seems that the username / password is always the one from the last mailer. The host names do differ though, having 127.0.0.1 and smtp.sendgrid.net as their values.

Also note that the code is being executed from a console script that extends from ContainerAwareCommand. When I test this in a normal controller, I don't have any issues. The username/password are different then (as they should).

By testing in a normal controller, I mean a controller that handles a HTTP request.. I wrote this little test:

``` PHP
    /**
     * @Route("/mail", name="_test_mail")
     */
    public function mailAction() {
        $mailer = $this->container->get('swiftmailer.mailer.sendgrid_mailer');
        echo "Sendgrid user: ".$mailer->getTransport()->getUsername();


        $mailer = $this->container->get('swiftmailer.mailer.local_mailer');
        echo "Local user: ".$mailer->getTransport()->getUsername();
        return new Response("Nou doei");
    }
```
